### ISSUE TITLE
Question: Where and when the dynamic analysis tool would be available

### ISSUE THREAD

**Issue by vmiheer** [upenn-acg/gpudrano-static-analysis_v1.0#1]
I liked your paper 😃. I was wondering when the dynamic analysis tools would be available.
Thank you.

**Comment by vmiheer** [comment]
@gatoWololo, any update on this? Thanks in advance!

**Comment by gatoWololo** [comment]
Whoops, sorry. I just saw this now. Yes, I have one bug that I want fixed for Dynamic Analysis, so I'll have it working and uploaded by next Friday!

**Comment by vmiheer** [comment]
Great thank you 👍.

**Comment by gatoWololo** [comment]
Hello! Sorry for the wait please see the separate [GpuDrano Dynamic Analysis Repo](https://github.com/upenn-acg/gpuDranoDynamicAnalysis) for the dynamic analysis!

**Comment by vmiheer** [comment]
Thank you!
